# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Tests and generate coverage"
  lane :tests_and_gen_coverage do
    # Run the pod install first
    cocoapods(try_repo_update_on_error: true)

    # Run the test
    xctest(workspace: "Nimble-Code-Challenge.xcworkspace", scheme: "Nimble-Code-Challenge", destination: "name=iPhone 11,OS=15.0")

    # Remove the previous report
    sh("rm -rf test_output")

    # Gen coverage with minimum 50% coverage percentage
    xcov(workspace: "Nimble-Code-Challenge.xcworkspace", scheme: "Nimble-Code-Challenge", output_directory: "./fastlane/test_output/", minimum_coverage_percentage: 50.0, only_project_targets: true)
  end
end
